### ISSUE TITLE
CAD Files Missing?

### ISSUE THREAD

**Issue by janoschsimon** [stuartpittaway/Super8FilmScanner#2]
Hey Stuart!
 i have download the Cad files and assembley and opende it in Freecad and it seems that the Microscope lens and sled design you show in the video are not in the cad files? i also found in the files a "film_sproket" that i didnt see in the assembly? do you have perhabs a "final" assembly that you can upload? :)  
cheers and thx Janosch

**Comment by stuartpittaway** [comment]
You can ignore the "film_sproket" it was an attempt at a 3d printed roller wheel/film gear - didn't work, and I used rubber wheels in the end as in the video.

All the files are in GITHUB that I have, however they also have some of the previous "didn't work" versions in it!!

If you open up the Assembly file in FreeCad - there are some parts which are not-visible, if you make these visible, you should start to see the same design I used on YouTube video.

CameraMount-RaspPiAdvanced.FCStd has multiple "body" parts in it, for the camera mount.

The assembly should look something like this...
![image](https://user-images.githubusercontent.com/1201909/176853126-b3b1b610-6531-47d3-9ee5-5a2554a48031.png)

**Comment by janoschsimon** [comment]
ARGGGGGGGGGG stupid me hahahah i didnt see the "invisible" parts hehhe now i can print everything thx a ton! :) take care Janosch
