### ISSUE TITLE
Microscope & Camera Sled CAD Files

### ISSUE THREAD

**Issue by wmshook** [stuartpittaway/Super8FilmScanner#4]
Great project! I've printed the 3D pieces and started assembling the scanner, however having trouble getting the camera assembly to mount and align properly. Could you please post the CAD files for the sled you created for the new camera and microscope lens. Also the clamps that are on the top. I'm building a version to accommodate 7" & 9" reels, and to scan both Super 8 & Reg 8mm film. I've located some old slot car foam tires to use for the pinch rollers. Once again Brilliant project!

**Comment by stuartpittaway** [comment]
Hi, all the files I used should be on GitHub, I don't have anything else!

**Comment by uepsie** [comment]
Hi wmshook

>  Could you please post the CAD files for the sled you created for the new camera and microscope lens. 

It's in https://github.com/stuartpittaway/Super8FilmScanner/blob/main/CameraMount-RaspPiAdvanced.FCStd you have to unhide them

**Comment by wmshook** [comment]
Stuart & uepsie
Found them!! Sweet! All I have to do is print them. Thanks heaps.
