### ISSUE TITLE
Camera CAD Files

### ISSUE THREAD

**Issue by dstein425** [stuartpittaway/Super8FilmScanner#5]
Hello Stuart,

Great project. I am working to convert your 8mm project to 16mm to capture old 16mm football films.  I noticed the CAD files from your final design do not appear in the git hub project, particularly the parts for the camera lens to focus the view, updated sled, and brackets to lock the camera in place.  Is it please possible to post them here on github?  Cheers!

Regards - Dave

**Comment by EuropaSteve** [comment]
You have to unhide the objects in FreeCad.

**Comment by dstein425** [comment]
Thank you @EuropaSteve that did it.  Cheers!
